# FUN AI 第2回 深層学習とPyTorch


## 深層学習とは

第0回でも触れたが、深層学習の定義として、

機械学習のうち

- 複雑なネットワークを用いる

- 人間が特徴量抽出を行わない

ものと覚えておけばとりあえずいいだろう。


## PyTorchとは
Pythonによる深層学習向けのフレームワーク。

公式より
>PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.

PytTorchとは、GPU及びCPUを使用した、深層学習のために最適化されたテンソルライブラリである。

資料でわからないことがあれば、https://pytorch.org/docs を調べれば大体は解決する

## 用語解説
***
- ### Python

    プログラミング言語の1つ。様々な分野のタスクを柔軟にこなせる。かつ、比較的書きやすいことから広く使われている。

- ### CPU

    Central Processing Unit の略。日本語にすると中央処理装置。PCには必ず搭載されており、キーボードやマウスなどから入力を受け取り、画面などへ出力を行う。コンピュータの制御・演算を行うことからコンピュータの頭脳と例えられることがある。

- ### GPU

    Graphics Processing Unit の略。元は描画処理特化のパーツだったが、近年GPGPU(General-purpose computing on GPU)という技術が発達し、その厖大な処理能力を、深層学習など他のタスクなどにも転用できるようになった。その結果、深層学習モデルの学習を今までよりも高速に行えるようになった。深層学習が流行した一端を担っている。

- ### テンソル

    ベクトルや行列の拡張表現。スカラを0階テンソル、ベクトルを1階テンソル。行列を2階テンソルとし、3階、4階…と次元が上がっていく。以下にサンプルコード示し、さらに解説する。

- ### ライブラリ

    プログラミング言語におけるライブラリとは、汎用性の高いプログラムをひとまとめにしたものをいう。ライブラリ単体では動作しないことが多い。ライブラリ(図書館)から便利なプログラム(本)を引き出して使うイメージ。

- ### フレームワーク

    プログラミングにおけるフレームワークとは、それ単体でアプリケーションなどを立ち上げることができるもののことを指す。PyTorchは深層学習フレームワークであり、ライブラリである。

In [3]:
import torch

$$
\mathbf{a} \,= (1, 2) \\
\mathbf{b} \,= \left(
    \begin{array}{c}
    1 \\
    2
    \end{array}
    \right)
$$

In [4]:
a = torch.Tensor([1, 2]) #行ベクトル
b = torch.Tensor([[1], [2]]) #列ベクトル
print(a)
print(b)

tensor([1., 2.])
tensor([[1.],
        [2.]])


$$
\mathbf{c} = \left(
    \begin{array}{cc}
    2 & 0\\
    0 & 1
    \end{array}
    \right)
$$    

In [5]:
c = torch.Tensor([[2, 0], [0, 1]]) # 2x2の行列
print(c)
print(c.size()) # size() でテンソルの大きさを確認できる

tensor([[2., 0.],
        [0., 1.]])
torch.Size([2, 2])


In [6]:
torch.matmul(a,b) # aとbの内積

tensor([5.])

テンソルに対して、基本的な演算を行える

まずは、cと同じく2x2の行列を宣言する

In [7]:
d = torch.Tensor([[1, 2], [3, 1]])
print(d)

tensor([[1., 2.],
        [3., 1.]])


テンソルは、和、差、積、スカラ倍、転置　などの計算を行える。詳しくは線形代数学Ⅰの履修内容になっているから、そちらにゆずる。

スカラ倍はいわゆるn倍、転置は行列の行と列を入れ替える演算

In [8]:
print(f'c+d:\n{c+d}\n')
print(f'c-d:\n{c-d}\n')
print(f'c*d:\n{torch.matmul(c, d)}\n')
print(f'd*c:\n{torch.matmul(d, c)}\n')
print(f'3*d:\n{3*d}\n')
print(f'd^T:\n{d.T}\n')

c+d:
tensor([[3., 2.],
        [3., 2.]])

c-d:
tensor([[ 1., -2.],
        [-3.,  0.]])

c*d:
tensor([[2., 4.],
        [3., 1.]])

d*c:
tensor([[2., 2.],
        [6., 1.]])

3*d:
tensor([[3., 6.],
        [9., 3.]])

d^T:
tensor([[1., 3.],
        [2., 1.]])



In [9]:
z = torch.randn([100]) # 正規分布からランダムに取り出す
print(z)
print(z.size())

tensor([ 0.1480,  0.0732, -0.5443,  0.1685, -2.6807, -0.1410,  1.0156, -0.9225,
         1.1610,  0.2851,  0.5309,  3.0502, -1.6575, -0.8706,  0.0137,  0.0588,
        -0.1175,  0.1806,  0.9786,  0.8148, -0.6449, -0.3561,  0.4260, -1.8613,
         1.4979, -1.4216,  0.4732, -0.7003, -1.0323, -0.7444, -1.0586,  1.0107,
         1.2049,  0.1647, -0.6105,  0.1196, -0.3770, -1.0901,  1.5098, -1.7290,
        -0.1519,  0.6617,  1.3732, -2.2841,  0.9291, -0.2603,  0.7460,  0.5014,
        -0.3092,  0.7129, -0.1863, -0.9438, -0.1964, -0.4245,  1.1192,  0.2058,
        -0.0567,  0.8524,  0.0787,  0.2663, -1.8375,  0.7442,  1.0664,  0.2522,
         0.0615, -1.1619, -0.6804, -1.5894,  1.2932, -0.0789, -0.9317, -0.4717,
        -0.4780, -0.5228,  1.4892,  0.4766, -0.6040,  0.2829,  0.3500,  0.3474,
         1.2880, -0.8480,  1.6878,  0.2679, -0.4824, -0.7087,  0.3128, -0.4737,
        -0.1775, -1.3897,  0.3307,  0.6758, -0.4363, -0.7377,  0.4812, -0.5355,
         0.7276, -1.8352, -0.9770, -0.62

In [14]:
# 3階以上のテンソルも宣言できる
a = torch.ones(3,3,3)
print(a)
print(a.size())

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([3, 3, 3])


演習問題

$$
\begin{align}
\mathbf{w} &= (1, 2, 3) \\
\mathbf{x} &= (x_1, x_2, x_3) \\
y &= \left(
    \begin{array}{ccc}
    y_{11} & y_{12} & y_{13} \\
    y_{21} & y_{22} & y_{23} \\
    y_{31} & y_{32} & y_{33}
    \end{array}
    \right)
\end{align}
$$
について、以下を計算せよ

(1) $\mathbf{w} \cdot \mathbf{w}^T$ 

(2) $\mathbf{w} \cdot \mathbf{x}^T$ 

(3) $\mathbf{x}^T \cdot \mathbf{w}$ 

(4) $\mathbf{x} \cdot y$

hint: (4)は行列をベクトルを集めたものだと考えて計算することもできる
$$
y = \left(
    \begin{array}{ccc}
    y_{11} & y_{12} & y_{13} \\
    y_{21} & y_{22} & y_{23} \\
    y_{31} & y_{32} & y_{33}
    \end{array}
    \right) = \left(
    \begin{array}{ccc}
     \mathbf{y_1}\\
     \mathbf{y_2}\\
     \mathbf{y_3}
    \end{array}
    \right)
    
$$

## 附録 Pythonの基本的な文法
Pythonは学部1年で触るProcessingとは異なる点が多い。最も大きな違いは、プログラミング上の意味の区切りが中括弧ではなく、空白。つまりはインデントで行われることだ。以下に基本的な文法を記すが、更に詳しいことを学びたい場合は、自分で調べるか、未来大学の競プロサークル FUNCoder に顔を出すといいだろう。 今回は、ノートブック形式で用意されているわけだから、気軽に値をいじって学びを深めてほしい。

### 代入
代入とは、保存しておきたいものに名前をつけておくことである。  
何でも入れられる箱に値を入れ、それに名前をつけると表現されることも多い。

Pythonでは、変数名 = 変数 の形で代入が可能である。

以下に x に 3 を代入する例を挙げる。

In [ ]:
x = 3

### 入出力

代入しただけでは、中身を確認することができない。そこで、入力と出力の例を示す。

最も基本的な入力と出力の方法は以下の通り。

入力には`input`を、出力には`print`を用いる。他にも色々あるが、とりあえずはこれらを覚えて良くと良いだろう。

以下を実行したら、入力用のポップアップがでるから、それに従って文字を入力してほしい。

In [ ]:
name = input()
print(name)

### 演算
Pythonでの基本的な演算は以下の通り。この他にビット演算子なども存在する。

In [ ]:
x, y = 2, 3
print(f'足し算:{x+y}')
print(f'引き算:{x-y}')
print(f'掛け算:{x*y}')
print(f'割り算:{x/y}')
print(f'切捨て除算:{x//y}')
print(f'あまり:{x%y}')
print(f'べき乗:{x**y}')
print(f'商とあまりのペア:{divmod(x, y)}')
print(f'等価演算子:{x==y}')
print(f'非等価演算子:{x!=y}')

### 関数
プログラミングにおける関数とは、数学での関数をより一般化した概念である。

ここでは、0個以上の引数を受け取り、何らかの動作をするものを関数。と定義する。

入出力で使った　`input` と `print` も関数の1つである。

In [ ]:
name = input('what is your name')
print(f'my name is {name}')

### データ型
プログラミングには、データ型(単に型とも)がある。型とは、あるデータの性質を表したものである。下の表はPythonの型の例である。型は他にもたくさん存在する。

|型|説明|宣言例|
|:-|:-|:-|
|int|整数|x = 3|
|float|小数(浮動小数点数)|x = 3.|
|str|文字列|x = '3'|
|bool|真偽値|x = True|

型の確認には`type`関数を使う。以下は str型のa というデータと解釈できる

In [ ]:
print(type('a'))

### 型変換(キャスト)
`input`関数を用いて入力を受け取った場合、その返り値はstr型になる。しかし、数値を扱いたいときにstrのままだと不都合である。

そのために型変換が用意されている。型変換は`型名(引数)`の形で一時的に型を変更できる。以下にその例を示す。

In [ ]:
x = '123' # 数値が入力されたことを想定されている
print(type(x))

int(x)
print(type(x))

x = int(x)
print(type(x))

### list
複数のデータをひとまとめにして扱うデータ型の1つに`list`型がある。

`[]`の中にコンマ区切りでデータを列挙する。これを外延表記という。他に内包表記とういものもあるが、これは集合論で内包表記をやったあとでもいいだろう。

In [ ]:
a = [1, 2 ,3, 4, 5]
print(a)
print(type(a))

list は float や str を要素に持つこともできる。

In [ ]:
b = ['a', 'i', 'u', 'e', 'o']
c = [1.1, 1.2, 1.3, 1.4, 1.5]

また、スライスといって、リストの要素にアクセスし取り出すこともできる

`list_object[start:end:step]`

と書き、startは開始位置、endは終了位置、stepは増分を表す。  
それぞれ省略可能で、省略した場合は初期値が使われる。初期値はそれぞれ`start=0`、`end=len(list_object)-1`(終端)、`step=1`
開始位置のみを指定した場合は、そのindexの値1つだけが取り出される

indexに0より小さい整数を指定することもできる。その場合は末尾を-1, その手前を-2, -3 が指定される

In [ ]:
print(a)
print(a[1])
print(a[len(a)-1])
print(a[-1])
print(b[::2])
print(b[1::2])

リストの末尾に要素(`item`)を追加するには`list_object.append(item)` を使う。

In [ ]:
print(a)
a.append(6)
print(a)

### if文
条件分岐をするにはif文を使う。
Pythonのif文は以下の通り。

もっとも単純なものは
```Python 
if 条件:
    処理
```

意味の区切りの箇所ではインデントを用いる。半角スペース4つもしくはTabを挿入する。どちらか好きな方で良いが、統一すること

if の条件を満たした時、満たさなかったときはif-elseを使う
```Python 
if 条件:
    処理
else:
    処理 # 条件を満たさなかったときの処理
```

条件を追加し、さらに複雑なこともできる。else if をつなげて elif を使う。  


```Python 
if 条件1:
    処理
elif 条件2:
    処理
else:
    処理
```

if文の中にif文を入れ子にすることもできる。

```Python
if 条件1:
    if 条件2:
        処理
    処理
else:
    処理
```

In [ ]:
x = 3
if x == 3:
    print('x is 3')
else:
    print("x isn't 3")

### for文
繰り返し処理(ループ)を行うためにはfor文を使う。  
Pythonのfor文は他の言語でいうforeachとほぼ一緒である。

文法は  
```Python 
for アイテム in イテラブル:
    処理
```
となる。詳しい意味はとりあえず置いておいて、処理の流れを解説する。

In [ ]:
for i in [2, 3, 5]:
    print(i)

listの先頭から1つずつ取り出して、それをiに代入しているのがわかるだろう。iに代入することができなくなったらループが終了する。

rangeという連番生成用の関数を用いて以下のように書くことも多い

In [ ]:
for i in range(10):
    print(i)

演習
以下の条件を満たすプログラムをかけ。

整数nが与えられる。  
1からnまでの整数を表示せよ。ただし、
- nが3の倍数ならば`Fizz`と出力する
- nが5の倍数ならば`Buzz`と出力する
- nが3と5の公倍数ならば`FizzBuzz`と出力する

In [ ]:
# このセルに書く

### 関数定義
自分で関数を定義することもできる。def は define の略。処理は複数行書くことができる。
```Python
def 関数名(引数):
    処理
    return 返り値
```

簡単な関数の例として、ある数nを受け取り、それを2倍にする関数を考える

In [ ]:
def twice(n):
    result = 2*n
    return result

'''
これも同じ
def twice(n):
    return 2*n

def twice(n):
    return n+n
'''

In [ ]:
print(twice(int(input())))

演習 ある数`n`を受け取り、1から`n`までの数をリストに格納する関数`FizzBuzz`を実装せよ。ただし、
- nが3の倍数ならば`Fizz`を格納する
- nが5の倍数ならば`Buzz`を格納する
- nが3と5の公倍数ならば`FizzBuzz`を格納する
- すべての要素はstr型で格納すること

In [ ]:




'''
解答例
def FizzBuzz(n):
    return [n%3//2*'Fizz' + n%5//4*'Buzz' or str(-~n) for n in range(n)]
'''

In [ ]:
# テスト
FizzBuzz(20)

### クラス定義

クラスとはデータや処理の定義をまとめた設計図のようなものだ。

あるクラスに引数を渡し、実際に使えるようにすることをインスタンスを生成する(インスタンス化とも)という。

インスタンスは、様々な処理を行うためのメソッドを持っている。メソッドとはクラス内で実装された関数のことを指す。

アトリビュートとはインスタンスが持つことができる変数のようなもののことを指す。


最も単純なクラス定義の仕方は以下の通り。
```Python
class ClassName:
    def __init__(self, arg):   # selfは自動的に読まれるから、このクラスはインスタンス化するときに見かけ上引数が1つ必要
        self.value = arg       # インスタンスにアトリビュートを追加
        
    def fnc(self):
        print(self.value)
 ```

`self` と `__init__()` について説明するが、難しいからよくわからなかったら、後から理解しても良い

### `__init__()` とは  
コンストラクタと呼ばれる初期化のためのメソッド。このメソッドはインスタンス生成時に自動的に呼び出される。  
他のメソッドでも用いるような共通しているアトリビュートはここで宣言する。  
そうしない場合、各メソッドで引数を代入する必要が出てくる。同じ値を使いまわすことを保証できないなどの不都合がある。


### `self` とは  
この`self`はインスタンス自身を指しており、`self`を代入することによって、インスタンスそのものをいじれるようになる。  
メソッドの第一引数に`self`を指定すると、自動的にインスタンスが代入されて呼び出される。

今回は、円の性質を持った`Circle`というクラスを実装する

実装するメソッドは
- radius 半径
- diameter 直径
- circumference 円周
- area 面積
の4つ

In [ ]:
# 円周率を使うためのモジュールをインポート
from math import pi

# クラス定義を行う
# arg は argument (引数)
# r は radius (半径) の略
# 変数名と関数は違うものにすること
# 関数を呼ぼうとしているのに変数を呼んでいるなどの事故が発生する

class Circle:
    def __init__(self,arg):
        self.r = arg

    def radius(self):
        return self.r

    def diameter(self):
        return self.r*2

    def circumference(self):
        return self.r*2*pi

    def area(self):
        return self.r**2*pi


In [ ]:
# xというCircleインスタンスを生成する
x = Circle(1)
# インスタンス化されたxはCircleが持つ様々なメソッド(関数)を呼ぶことができる

print(x.radius())
print(x.diameter())
print(x.circumference())
print(x.area())
print(type(x))

球の性質を持った`Ball`クラスを実装せよ

ただし、インスタンス化する際に半径を引数に取ること

実装するメソッドは
- 半径
- 直径
- 表面積
- 体積
- 余力がアレばオリジナルのものを追加する
適切なメソッド名をつけること

これで第2回を終了とする