# FUN AI 第2回 深層学習とPyTorch


## 深層学習とは

第0回でも触れたが、深層学習の定義として、

機械学習のうち

- 複雑なネットワークを用いる

- 人間が特徴量抽出を行わない

ものと覚えておけばとりあえずいいだろう。


## PyTorchとは
Pythonによる深層学習向けのフレームワーク。

公式より
>PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.

PytTorchとは、GPU及びCPUを使用した、深層学習のために最適化されたテンソルライブラリである。

資料でわからないことがあれば、https://pytorch.org/docs を調べれば大体は解決する

## 用語解説

Python -> プログラミング言語の1つ。様々な分野のタスクを柔軟にこなせる。かつ、比較的書きやすいことから広く使われている。

CPU -> Central Processing Unit の略。日本語にすると中央処理装置。PCには必ず搭載されており、キーボードやマウスなどから入力を受け取り、画面などへ出力を行う。コンピュータの制御・演算を行うことからコンピュータの頭脳と例えられることがある。

GPU -> Graphics Processing Unit の略。元は描画処理特化のパーツだったが、近年GPGPU(General-purpose computing on GPU)という技術が発達し、その厖大な処理能力を、深層学習など他のタスクなどにも転用できるようになった。その結果、深層学習モデルの学習を今までよりも高速に行えるようになった。深層学習が流行した一端を担っている。

テンソル -> ベクトルや行列の拡張表現。スカラを0階テンソル、ベクトルを1階テンソル。行列を2階テンソルとし、3階、4階…と次元が上がっていく。以下にサンプルコード示し、さらに解説する。

ライブラリ -> プログラミング言語におけるライブラリとは、汎用性の高いプログラムをひとまとめにしたものをいう。ライブラリ単体では動作しないことが多い。ライブラリ(図書館)から便利なプログラム(本)を引き出して使うイメージ。

フレームワーク -> プログラミングにおけるフレームワークとは、それ単体でアプリケーションなどを立ち上げることができるもののことを指す。PyTorchは深層学習フレームワークであり、ライブラリである。

In [1]:
import torch

$$
\mathbf{a} \,= (1, 2) \\
\mathbf{b} \,= \left(
    \begin{array}{c}
    1 \\
    2
    \end{array}
    \right)
$$

In [2]:
a = torch.Tensor([1, 2]) #行ベクトル
b = torch.Tensor([[1], [2]]) #列ベクトル
print(a)
print(b)

tensor([1., 2.])
tensor([[1.],
        [2.]])


$$
\mathbf{c} = \left(
    \begin{array}{cc}
    2 & 0\\
    0 & 1
    \end{array}
    \right)
$$    

In [3]:
c = torch.Tensor([[2, 0], [0, 1]]) # 2x2の行列
print(c)
print(c.size()) # size() でテンソルの大きさを確認できる

tensor([[2., 0.],
        [0., 1.]])
torch.Size([2, 2])


In [4]:
torch.matmul(a,b) # aとbの内積

tensor([5.])

テンソルに対して、基本的な演算を行える

まずは、cと同じく2x2の行列を宣言する

In [5]:
d = torch.Tensor([[1, 2], [3, 1]])
print(d)

tensor([[1., 2.],
        [3., 1.]])


テンソルは、和、差、積、スカラ倍、転置　などの計算を行える。詳しくは線形代数学Ⅰの履修内容になっているから、そちらにゆずる。

スカラ倍はいわゆるn倍、転置は行列の行と列を入れ替える演算

In [6]:
print(f'c+d:\n{c+d}\n')
print(f'c-d:\n{c-d}\n')
print(f'c*d:\n{torch.matmul(c, d)}\n')
print(f'd*c:\n{torch.matmul(d, c)}\n')
print(f'3*d:\n{3*d}\n')
print(f'd^T:\n{d.T}\n')

c+d:
tensor([[3., 2.],
        [3., 2.]])

c-d:
tensor([[ 1., -2.],
        [-3.,  0.]])

c*d:
tensor([[2., 4.],
        [3., 1.]])

d*c:
tensor([[2., 2.],
        [6., 1.]])

3*d:
tensor([[3., 6.],
        [9., 3.]])

d^T:
tensor([[1., 3.],
        [2., 1.]])



In [7]:
z = torch.randn([100]) # 正規分布からランダムに取り出す
print(z)
print(z.size())

tensor([ 1.0519, -0.0645,  0.0273,  0.3637,  0.0766,  0.5249,  0.3954, -0.7209,
        -0.0616,  0.7480,  0.5004,  0.6943,  2.3398,  1.1207, -0.3548,  0.2838,
        -0.3148,  0.7196,  0.1566, -0.1723, -0.2954,  1.3535,  0.2098, -2.6082,
        -0.8416, -1.4285, -0.2628, -1.9739,  0.7863, -0.9306,  0.9394, -0.8896,
         1.1766,  0.7951, -0.2030, -0.8573, -0.5858,  0.4666, -1.0106,  1.3809,
         1.2157, -0.7512,  0.7050, -0.3169,  0.7310, -0.3070, -0.1989, -0.3275,
        -0.0459, -1.0946, -0.5937, -1.2438, -0.4862, -0.2881, -1.3332,  1.1361,
         0.8391,  1.0147, -0.4156, -0.0106,  2.1524,  0.7468, -0.5361,  0.0484,
        -0.6893,  0.6399,  0.5670, -0.5737, -1.0556,  0.7967, -0.7803, -1.0265,
         0.2963,  0.6912,  0.3057, -1.7011,  0.1315,  1.5544, -0.4742, -0.5769,
        -1.3889,  1.4070,  0.3627,  0.0367,  0.0777, -1.0405, -1.3172,  0.8097,
         0.1165, -0.6504,  1.0830, -0.1918,  0.5579,  0.4584, -1.2918, -0.5396,
         1.2470,  1.4069, -0.0531, -0.79

In [8]:
# 3階以上のテンソルも宣言できる
a = torch.ones([2, 2, 2])
print(a)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])


演習問題

$$
\begin{align}
\mathbf{w} &= (1, 2, 3) \\
\mathbf{x} &= (x_1, x_2, x_3) \\
\mathbf{y} &= \left(
    \begin{array}{ccc}
    y_{11} & y_{12} & y_{13} \\
    y_{21} & y_{22} & y_{23} \\
    y_{31} & y_{32} & y_{33}
    \end{array}
    \right)
\end{align}
$$
について、以下を計算せよ

(1) $\mathbf{w} \cdot \mathbf{w}^T$ 

(2) $\mathbf{w} \cdot \mathbf{x}^T$ 

(3) $\mathbf{x} \cdot \mathbf{y}$

## 附録 Pythonの基本的な文法
Pythonは学部1年で触るProcessingとは異なる点が多い。最も大きな違いは、プログラミング上の意味の区切りが中括弧ではなく、空白。つまりはインデントで行われることだ。以下に基本的な文法を記すが、更に詳しいことを学びたい場合は、自分で調べるか、未来大学の競プロサークル FUNCoder に顔を出すといいだろう。

### 代入
代入とは、保存しておきたいものに名前をつけておくことである。  
何でも入れられる箱に値を入れ、それに名前をつけると表現されることも多い。

Pythonでは、変数名 = 変数 の形で代入が可能である。

以下に x に 3 を代入する例を挙げる。

In [9]:
x = 3

### 入出力

代入しただけでは、中身を確認することができない。そこで、入力と出力の例を示す。

最も基本的な入力と出力の方法は以下の通り。

入力には`input`を、出力には`print`を用いる。他にも色々あるが、とりあえずはこれらを覚えて良くと良いだろう。

以下を実行したら、入力用のポップアップがでるから、それに従って文字を入力してほしい。

In [10]:
name = input()
print(name)

### 演算
Pythonでの基本的な演算は以下の通り。この他にビット演算子なども存在する。

In [11]:
x, y = 2, 3
print(f'足し算:{x+y}')
print(f'引き算:{x-y}')
print(f'掛け算:{x*y}')
print(f'割り算:{x/y}')
print(f'切捨て除算:{x//y}')
print(f'あまり:{x%y}')
print(f'べき乗:{x**y}')
print(f'商とあまりのペア:{divmod(x, y)}')

足し算:5
引き算:-1
掛け算:6
割り算:0.6666666666666666
切捨て除算:0
あまり:2
べき乗:8
商とあまりのペア:(0, 2)


### 関数
プログラミングにおける関数とは、数学での関数をより一般化した概念である。

ここでは、0個以上の引数を受け取り、何らかの動作をするものを関数。と定義する。

入出力で使った　`input` と `print` も関数の1つである。

In [12]:
name = input('what is your name')
print(f'my name is {name}')

my name is 


### データ型
プログラミングには、データ型(単に型とも)がある。型とは、あるデータの性質を表したものである。下の表はPythonの型の例である。型は他にもたくさん存在する。

|型|説明|宣言例|
|:-|:-|:-|
|int|整数|x = 3|
|float|浮動小数点数|x = 3.|
|str|文字列|x = '3'|
|bool|真偽値|x = True|

型の確認には`type`関数を使う。以下は str型のa というデータと解釈できる

In [13]:
print(type('a'))

<class 'str'>


### list
複数のデータをひとまとめにして扱うデータ型の1つに`list`型がある。

In [14]:
a = [1, 2 ,3, 4, 5]
print(a)
print(type(a))

[1, 2, 3, 4, 5]
<class 'list'>


list は float や str を要素に持つこともできる。

In [15]:
b = ['a', 'i', 'u', 'e', 'o']
c = [1.1, 1.2, 1.3, 1.4, 1.5]

また、スライスといって、リストの要素にアクセスし取り出すこともできる

`list_object[start:end:step]`

と書き、startは開始位置、endは終了位置、stepは増分を表す。  
それぞれ省略可能で、省略した場合は初期値が使われる。初期値はそれぞれ`start=0`、`end=len(list_object)-1`(終端)、`step=1`
開始位置のみを指定した場合は、そのindexの値1つだけが取り出される

indexに0より小さい整数を指定することもできる。その場合は末尾を-1, その手前を-2, -3 が指定される

In [36]:
print(a)
print(a[1])
print(a[len(a)-1])
print(a[-1])
print(b[::2])
print(b[1::2])

[1, 2, 3, 4, 5]
2
5
5
['a', 'u', 'o']
['i', 'e']


### if文
条件分岐をするにはif文を使う。
Pythonのif文は以下の通り。

もっとも単純なものは
```Python 
if 条件:
    処理
```

意味の区切りの箇所ではインデントを用いる。半角スペース4つもしくはTabを挿入する。どちらか好きな方で良いが、統一すること

if の条件を満たした時、満たさなかったときはif-elseを使う
```Python 
if 条件:
    処理
else:
    処理 # 条件を満たさなかったときの処理
```

条件を追加し、さらに複雑なこともできる。else if をつなげて elif を使う。  


```Python 
if 条件1:
    処理
elif 条件2:
    処理
else:
    処理
```

if文の中にif文を入れ子にすることもできる。

```Python
if 条件1:
    if 条件2:
        処理
    処理
else:
    処理
```

In [34]:
x = 3
if x == 3:
    print('x is 3')
else:
    print("x isn't 3")

x is 3


### for文
繰り返し処理(ループ)を行うためにはfor文を使う。  
Pythonのfor文は他の言語でいうforeachとほぼ一緒である。

文法は  
```Python 
for アイテム in イテラブル:
    処理
```
となる。詳しい意味はとりあえず置いておいて、処理の流れを解説する。

In [18]:
for i in [2, 3, 5]:
    print(i)

2
3
5


listの先頭から1つずつ取り出して、それをiに代入しているのがわかるだろう。iに代入することができなくなったらループが終了する。

rangeという連番生成用の関数を用いて以下のように書くことも多い

In [19]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


演習
以下の条件を満たすプログラムをかけ。

整数nが与えられる。  
1からnまでの整数を表示せよ。ただし、
- nが3の倍数ならば`Fizz`と出力する
- nが5の倍数ならば`Buzz`と出力する
- nが3と5の公倍数ならば`FizzBuzz`と出力する